### ISSUE TITLE
Unable to create master voice channel

### ISSUE THREAD

**Issue by Frerduro** [DynamicaBot/Dynamica-V2#83]
[2023-05-29] [10:19:36] › ✘  error     Error while running command create PrismaClientKnownRequestError: 
Invalid `prisma.primary.create()` invocation:
Foreign key constraint failed on the field: `foreign key`
    at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:30856:12)
    at async DB2._request (/app/node_modules/@prisma/client/runtime/index.js:31836:16)
    at Primaries2.initialise (/app/src/classes/Primaries.ts:76:21)
    at CreateCommand2.CreateCommand2.response (/app/src/commands/CreateCommand.ts:47:24)
    at Commands2.Commands2.run (/app/src/classes/Commands.ts:94:7) {
  code: 'P2003',
  clientVersion: '4.5.0',
  meta: { field_name: 'foreign key' }
}
[2023-05-29] [10:19:36] › ✘  error     Error while running command create PrismaClientKnownRequestError: 
Invalid `prisma.primary.create()` invocation:
Foreign key constraint failed on the field: `foreign key`
    at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:30856:12)
    at async DB2._request (/app/node_modules/@prisma/client/runtime/index.js:31836:16)
    at Primaries2.initialise (/app/src/classes/Primaries.ts:76:21)
    at CreateCommand2.CreateCommand2.response (/app/src/commands/CreateCommand.ts:47:24)
    at Commands2.Commands2.run (/app/src/classes/Commands.ts:94:7) {
  code: 'P2003',
  clientVersion: '4.5.0',
  meta: { field_name: 'foreign key' }
}

**Comment by Frerduro** [comment]
im an idiot sorry about this.
